config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: %i[index new show create destroy] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_length_of :comment, :minimum => 6
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :overview, :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list.destroy

    redirect_to lists_path, notice: 'List was successfully destroyed'
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add movie to <%= @list.name %></h3>

        <%= simple_form_for [@list, @bookmark] do |f| %>
          <% if @bookmark.errors.any? %>
            <div class="alert alert-danger">
              <h5>You must correct these errors</h5>
              <ul>
                <% @bookmark.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <%= f.input :comment %>
          <%= f.association :movie, collection: Movie.all - @list.movies %>
          <%= f.submit class: 'btn btn-primary' %> or
          <%= link_to 'Cancel', list_path(@list), class: 'text-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watchlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/bookmark.htmk.erb
<div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
  <div class="bg-white rounded shadow h-100">
    <%= image_tag movie.poster_url, alt: movie.title, class: 'movie-img rounded-top' %>

    <div class="p-3 rounded-bottom d-flex flex-column">
      <strong>
        <%= movie.title %>

        <span class="text-muted font-weight-normal">•
          <%= movie.rating %> <i class="fas fa-star text-info"></i>
        </span>
      </strong>

      <small class="text-muted">
        <%= movie.overview %>
      </small>

      <div class="d-flex align-items-end justify-content-between pt-4">
        <div>
          <i class="fas fa-quote-left mr-2"></i>
          <small class="flex-grow-1"><%= bookmark.comment %></small>
        </div>

        <small class="text-right flex-shrink-0">
          <%= link_to bookmark_path(bookmark), method: :delete,
            data: { confirm: "Are you sure you want to remove #{movie.title} from your #{list.name} list"},
            class: 'text-danger' do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </small>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1>Save any kind of movies</h1>
    <h3 class="typed-js"></h3>
  </div>
</div>

<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
    <%= link_to new_list_path, class: 'btn btn-primary' do %>
      <i class="fas fa-plus"></i> Add new list
    <% end %>
  </div>

  <div class="row">
    <% @lists.each do |list| %>
      <div class="co-12 colsm-6 col-md-4">
        <%= link_to list_path(list), class:'text-decoration-none' do %>
          <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>

        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
          <%= f.submit class: 'btn btn-primary' %> or
          <%= link_to 'Cancel', lists_path, class: 'text-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="position-relative">
  <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))>
    <h1><%= @list.name %></h1>
  </div>

  <span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
</div>

<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block">
      <small>
        <em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em>
      </small>
    </span>

    <div>
      <%= link_to new_list_bookmark_path(@list), class: 'btn btn-primary' do %>
        <i class="fas fa-plus"></i> Add movie
      <% end %>
      <%= link_to list_path(@list), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this list?' } do %>
        <i class="fas fa-trash-alt"></i> Delete list
      <% end %>
    </div>
  </div>

  <div class="row my-2">
    <% @list.bookmarks.each do |bookmark| %>
      <%= render 'bookmark', bookmark: bookmark, list: @list, movie: bookmark.movie %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "My lists", lists_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "New list", new_list_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>